spring:
  application:
    name: backend # Specifies the name of the application
  jpa:
    hibernate:
      ddl-auto: update # Specifies the behavior of Hibernate when it creates or updates database tables based on the entities defined in the application
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect # Specifies the dialect to use when communicating with the PostgreSQL database
  datasource:
    url: jdbc:postgresql://localhost:5432/engine # Specifies the URL of the PostgreSQL database
    username: postgres # Specifies the username for accessing the PostgreSQL database
    password: # Specifies the password for accessing the PostgreSQL database
  mail:
    host: smtp.gmail.com
    port: 587
    username: drissihoucem2002@gmail.com
    password: maefjbbhwvnexfjd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    context-path: /backend

camunda:
  bpm:
    enabled: true # Specifies whether to enable Camunda BPM or not
    admin-user:
      id: camunda # Specifies the user ID of the Camunda BPM admin user
      password: camunda # Specifies the password of the Camunda BPM admin user
    database:
      schema-update: true # Specifies whether to update the Camunda BPM schema automatically or not
    filter:
      create: All # Specifies which filters to create for Camunda BPM
    authorization:
      enabled: true # Specifies whether to enable Camunda BPM authorization or not
    history-level: full # Specifies the level of detail for the Camunda BPM history
    auto-deployment-enabled: false # Specifies whether to enable auto-deployment of BPMN files or not
    default-number-of-retries: 3 # Specifies the default number of retries for failed Camunda BPM jobs
    job-execution:
      enabled: true # Specifies whether to enable Camunda BPM job execution or not

flowvioo:
  app:
    jwtSecret: flowviooSecretKey
    jwtExpirationMs: 86400000
    jwtRefreshExpirationMs: 86400000